token:
  expiration_time: 864000000 
  secret: '{cipher}AYA0Yg72c5/bLPN4oMR2bsKN8ngD9M/pZPb0fm5yNnTugK/q4uI7IWK966hjibneJfPZO5kctwTC9HuHnxlVv9WbmnN1w6uVoM1vTlj0Zkt0AlxvXVf/YDiyt/wqzyI16M3kX4nhYN7tbU5QGgAhQmFP4yS0d/rrdr2z3gEZuTqxccCXCrCpu1HgN6XmSASWZgl4HxkBvmz88++WjvusY/KLmCHxfqWXgFS9yuErw0HQhcejiW6+Z+cTzlNCWzl43uStg29U2XXO1P6mTLVPoMESSyU5NTOMpY3oxsc5zdu5MDqoCKhFovn6Ggz4UIp4VQ4QjiayuCzPkVOlGpfRwW0u8Rm8h6E6TkXSnw1TOJilSu9uOt6ytoMxlp67RSlYOTGzoeUrK4lzoZ8dh8E0K1H+sJjIZZi0Mhz+utVuKPK1DsF2Tx8TR+zxnVkYC/ogKByye2z+14/tGXMOSDNamOHFOCI2OVFCN7Lhm2hBv7vY1DBi586y32Z0hKP9i80uW1umUUZsIXTaAZFV3Hk+Okviqi+VRj902amEMhD9o0a4ABJNX0xFjPJLWKlN2ATy4O5U7EwJD3stylqcTWn7qlqUeqem1fOzpaCXfllTKY7ucLp5QPeJrAIgIomCNn8SeMg='

gateway:
  ip: 172.18.0.1
