spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 86400000
  secret: '{cipher}Aln/onPp4whwfkWQsYQ6xIUcCJS5g/h6fDQb+Wr2jdop8AsCxmkYo5aL2uk5xLsxDhQxnlav6egt0lmOCn0DbCW6acK+rEm6w6fPz3vEXR2l0J8gztOAZjOB+7PEVMcuyXNBxIagNXOaHFLLw/sFbze9hvB8MWQtaIJYdccSKPDNz3zqeZW2EIXRfSlVULhaYxNET75ojK6jqb3TACd9p358lQwe82ZB75yf0oyDjP4BqpVzsED5TZpDF1u3GZhKZ0nK+sGOksRNSfX0bwEgN9x19iphtLc98OzVkldgXyc6DikLVGqTaLQ7PqCzfbtdcOv+RZhPYDqBQjxLgIp0Q9IdO/cK6tx6DT3zua7GkbMJJzTOfG7GcpEqq876EPdBLhvaCd4wxBYU0aXha37pUbjTxggMs7GYfxORiRNmpRQiHWYYskSiQO/7lovKT3guIdaZRMLA0mYvmvfxwdOfvvBQ33i/7fmVb4RwmZi7sNgSLR5TWCu35z6FLBiv4iW1bw9tD5WheqXrrHug25z11TtJuimK8z6MwGzGYl88zZQajfrwVvmgcFAK10tLPmErcQfraSZiutoWIBdktabh4mIKk83yf9HqqfE4iSYiL3Ag=='
gateway:
  ip: 127.0.0.1

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order-is-empty: User's order is empty.
