spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 5640000010
  # secret: YOUR_SECRETKEY_20240202_FOR_SPRING_CLOUD_LOGIN
  # secret: 20240206_YOUR_SECRETKEY_20240202_FOR_SPRING_CLOUD_LOGIN_#1
  # secret: APPLE_YOUR_SECRETKEY_20240202_FOR_SPRING_CLOUD_LOGIN_#1
  # secret: BANANA_YOUR_SECRETKEY_20240202_FOR_SPRING_CLOUD_LOGIN_#1
  secret: RabbitMQTest
gateway:
  ip: 127.0.0.1
