spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: '{cipher}AYCWqVa94YPjvpFxFKRHWS4afRPWg1n+MWXGbKBhGE0XrpytowId5sJQgQsxW3JOVqGkwzyUgrQRvXGicLSti0vD8jZnYg4DXloIST2Pl8ZgO9fCyTr/pVfryIhu3gBAUT+jaXP4uiFpnPLm+dSblvXmnG5hVDj24VOJqM3ewyI4lfReNlDckKdvv5TTzjECfanYSHeyizUdS2y8o3sn0yjkYlQjgkdadvAddSCsZ1I2OA5tsyDspwLwwIgqxbj2drTGbnsqdO43WZ4Su2p4dMXqs1P6wd4qmvVJyGqaKlQhrtaq0owAt6AgU/WzIJ8COTGILTA3BOlZvQetMK2kdxb5WBNw421Miwye68I2gRh29/5fWMKZF5j3GsntjZyH4b22ttFQUhu8f/ox5NF2x6jujOOBCY1KMQ3HrnVMfsenjUcYEIVYtVPZsp5HAKYG7LQteU7fRJHKb0oXtlMjdto0ZBQAY6FpF/+2rsUfzPMnt8gICUZMa2nEET9E0/v1I3dyuxPiSm8z5ZEcelACMp88LuOLDEgignn7LvoOIb5r1xCJwfHRacoHzWGQePcV03Q='

app:
  payment:
    apiToken: '{cipher}AYBiqIwR47EUXVMiUUgQA3MY65xE1hPU53UhatBAH5eoDPTnWnUBggXrGYtBCgy2+wpCZieRQLYA1w+pA6U81RdD/FyEVKwxEoPfuwgQaaFNPBkbxKc1Ag1ot1jpGM+P5uiROQ5bSd40Dh6Yzf+crbZwpe4szLddmJ7fs4NaHCT4OEsRrEpe2wPZwnGyTQQyH05N4O7WVhNFnSqS8IWHnmRjkKTgMW8gFYt1f1pZ8uUaFo71vjQ9zrcwjtIGJuXepq2001XW3/y+oKkXLmoHlbWlUxS9auuRI7QpZIqBjrIqjQ74pdHsyVwIyl6I690UleggooE8WmSs/EFQipsLOLJG8ShLisuKnZcG4xn+cw2OTt8YNCZpH2HojSCVP5RmsFnrvoli3IbdLNme8dD95yg7jQZvGZLyZGtA4HNdqerXCtDSleFcxvzCu3LW1AOv0lhfxMT70qBXlMjX2bHtnmCJ/ZABESX6nXoUB3GFSmWHvmEr0pixEQMOmIb77p6i0t6NOSgz2Qt7RjxnhgMlbUBsp9l83cHeDt4E1BDkHp8VccghjEfAI0jVoSPULOQdOVs='

logging:
  level:
    root: INFO
