spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}48bcd1447907dedf2a5a8ec7ca893d700a7a1e267d670bad48f30501f91085f5'

token:
  expiration_time: 864000000
  secret: new_user_token_20220525

gateway:
  ip: 127.0.0.1
