spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 

token:
  expiration_time: 86400000
  secret: '{cipher}AQBc2gzIET++nplSofhKaUK1lYDKYvYeSMkqkQZvtda4DAfzx1GeAPmgkZW2KQG/Ay43OZDLr1cuNdLb+EcRYNLGUEO7tsIU8Tq/gaEyoC9EHQCEndTVdEFf/Hc8lPnX4mXjAPokh9HVZiThcYfKev8mxsnBG1cuzwejV0qLZAWrD2WW51/56GwDDo27Xwo3XTx7zhkM1NUftradjls/oMGe1HhLc6O3wj6xuqep6D3UG5KcAmeZ1E4oJ52aR0cRQqw7V6RHuIeybaAUx/Qz5EKWTtQf2NejALtUvkjdE7Jd5tdHoCCsKmwvkVWgCUyzojvimnegO+fcIzj+Rb97JrgtoAUABc57aAOQNyInOT51V2x9ssg01UToBxHQ18XDtL19C6zoFEV5pefKgxN2HAVyFvwfuFvtoWeaSxAhMrEPKw=='
gateway:
  ip: 127.0.0.1

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order-is-empty: User's order is empty.
